import React, { createContext, useContext, useEffect, useState } from "react";

const dict = {
  en: {
    app_name: "RescueBite",
    tagline: "Save food. Feed hope.",
    hero_title: "Turn surplus into second chances",
    hero_sub: "A simple platform connecting restaurants, beneficiaries, and volunteers to rescue good food that would otherwise be wasted.",
    get_started: "Get started",
    login: "Login",
    signup: "Sign up",
    logout: "Log out",
    how_it_works: "How it works",
    step_restaurants: "Restaurants list surplus food",
    step_restaurants_d: "Add leftover meals, bread, or catering in seconds. Choose pickup or delivery.",
    step_beneficiaries: "Beneficiaries claim meals",
    step_beneficiaries_d: "Browse nearby listings and request pickup or delivery with a single click.",
    step_volunteers: "Volunteers deliver hope",
    step_volunteers_d: "Pick up approved requests, drive the last mile, and update the status in real time.",
    for_restaurants: "For restaurants",
    for_beneficiaries: "For beneficiaries",
    for_volunteers: "For volunteers",
    email: "Email",
    password: "Password",
    name: "Full name",
    phone: "Phone (optional)",
    role: "I am a...",
    restaurant: "Restaurant",
    beneficiary: "Beneficiary",
    volunteer: "Volunteer",
    no_account: "No account yet?",
    have_account: "Already registered?",
    dashboard: "Dashboard",
    browse: "Browse food",
    my_requests: "My requests",
    my_listings: "My listings",
    requests_inbox: "Requests inbox",
    deliveries: "Deliveries",
    available_deliveries: "Available deliveries",
    add_food: "Add food",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    confirm: "Confirm",
    title: "Title",
    description: "Description",
    quantity: "Quantity",
    price: "Price",
    free: "Free",
    location: "Location",
    image_url: "Image URL",
    status: "Status",
    actions: "Actions",
    available: "Available",
    reserved: "Reserved",
    completed: "Completed",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    on_the_way: "On the way",
    picked_up: "Picked up",
    delivered: "Delivered",
    pickup: "Pickup",
    delivery: "Delivery",
    delivery_address: "Delivery address",
    notes: "Notes (optional)",
    request_food: "Request this food",
    back: "Back",
    accept: "Accept",
    reject: "Reject",
    mark_picked_up: "Mark as picked up",
    mark_delivered: "Mark as delivered",
    accept_delivery: "Accept delivery",
    no_data: "Nothing to show yet.",
    search_placeholder: "Search food, location...",
    stats_total: "Total listings",
    stats_available: "Available",
    stats_reserved: "Reserved",
    stats_completed: "Completed",
    stats_pending: "Pending requests",
    landing_cta: "Start rescuing food",
    landing_cta_sub: "It takes less than a minute to create an account.",
    our_impact: "Our shared impact",
    meals_saved: "Meals saved",
    cities_active: "Cities active",
    partners: "Restaurant partners",
    login_title: "Welcome back",
    login_sub: "Sign in to continue rescuing food.",
    register_title: "Create your account",
    register_sub: "Join the movement — pick a role to get started.",
    food_details: "Food details",
    request_type: "How do you want it?",
    delivery_placeholder: "Street, building, notes for the volunteer...",
    requested_on: "Requested on",
    from: "From",
    to: "To",
    admin_overview: "Overview",
    admin_users: "Users",
    admin_foods: "Foods",
    admin_requests: "Requests",
    admin_deliveries: "Deliveries",
    admin_analytics: "Analytics",
    admin_dashboard: "Admin Dashboard",
    total_users: "Total users",
    total_restaurants: "Restaurants",
    total_beneficiaries: "Beneficiaries",
    total_volunteers: "Volunteers",
    active_listings: "Active listings",
    stats_meals_saved: "Meals saved",
    active_deliveries: "Active deliveries",
    success_rate: "Success rate",
    waste_reduction_rate: "Waste reduction",
    joined: "Joined",
    role_label: "Role",
    delete_user: "Delete user",
    confirm_delete: "Are you sure you want to delete this user?",
    user_deleted: "Account disabled",
    no_users: "No users yet.",
  },
  ar: {
    app_name: "RescueBite",
    tagline: "أنقذ الطعام. أنعش الأمل.",
    hero_title: "حوّل الفائض إلى فرصة ثانية",
    hero_sub: "منصة بسيطة تربط المطاعم، المستفيدين، والمتطوعين لإنقاذ الطعام الذي كان سيُهدر.",
    get_started: "ابدأ الآن",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل خروج",
    how_it_works: "كيف تعمل المنصة",
    step_restaurants: "المطاعم تُضيف الفائض",
    step_restaurants_d: "أضف الوجبات الفائضة أو الخبز أو بقايا حفلات خلال ثوانٍ. اختر استلام أو توصيل.",
    step_beneficiaries: "المستفيدون يطلبون الوجبات",
    step_beneficiaries_d: "تصفّح الوجبات القريبة واطلب الاستلام أو التوصيل بنقرة واحدة.",
    step_volunteers: "المتطوعون يوصلون الأمل",
    step_volunteers_d: "استلم الطلبات الموافق عليها وسلّمها، مع تحديث الحالة لحظة بلحظة.",
    for_restaurants: "للمطاعم",
    for_beneficiaries: "للمستفيدين",
    for_volunteers: "للمتطوعين",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم الكامل",
    phone: "الجوال (اختياري)",
    role: "أنا...",
    restaurant: "مطعم",
    beneficiary: "مستفيد",
    volunteer: "متطوع",
    no_account: "ليس لديك حساب؟",
    have_account: "لديك حساب بالفعل؟",
    dashboard: "لوحة التحكم",
    browse: "تصفح الطعام",
    my_requests: "طلباتي",
    my_listings: "إعلاناتي",
    requests_inbox: "طلبات واردة",
    deliveries: "التوصيلات",
    available_deliveries: "توصيلات متاحة",
    add_food: "أضف طعاماً",
    edit: "تعديل",
    delete: "حذف",
    cancel: "إلغاء",
    save: "حفظ",
    confirm: "تأكيد",
    title: "العنوان",
    description: "الوصف",
    quantity: "الكمية",
    price: "السعر",
    free: "مجاناً",
    location: "الموقع",
    image_url: "رابط صورة",
    status: "الحالة",
    actions: "الإجراءات",
    available: "متاح",
    reserved: "محجوز",
    completed: "مكتمل",
    pending: "قيد الانتظار",
    accepted: "مقبول",
    rejected: "مرفوض",
    on_the_way: "في الطريق",
    picked_up: "تم الاستلام",
    delivered: "تم التسليم",
    pickup: "استلام",
    delivery: "توصيل",
    delivery_address: "عنوان التوصيل",
    notes: "ملاحظات (اختياري)",
    request_food: "اطلب هذا الطعام",
    back: "رجوع",
    accept: "قبول",
    reject: "رفض",
    mark_picked_up: "تم الاستلام",
    mark_delivered: "تم التسليم",
    accept_delivery: "قبول التوصيل",
    no_data: "لا يوجد شيء لعرضه حالياً.",
    search_placeholder: "ابحث عن طعام أو موقع...",
    stats_total: "إجمالي الإعلانات",
    stats_available: "متاح",
    stats_reserved: "محجوز",
    stats_completed: "مكتمل",
    stats_pending: "طلبات معلقة",
    landing_cta: "ابدأ بإنقاذ الطعام",
    landing_cta_sub: "يستغرق إنشاء الحساب أقل من دقيقة.",
    our_impact: "أثرنا المشترك",
    meals_saved: "وجبة تم إنقاذها",
    cities_active: "مدن مفعّلة",
    partners: "مطاعم شريكة",
    login_title: "مرحباً من جديد",
    login_sub: "سجّل دخولك لمتابعة إنقاذ الطعام.",
    register_title: "أنشئ حسابك",
    register_sub: "انضم إلى الحركة — اختر دورك وابدأ.",
    food_details: "تفاصيل الطعام",
    request_type: "كيف تريد الاستلام؟",
    delivery_placeholder: "الشارع، المبنى، ملاحظات للمتطوع...",
    requested_on: "تاريخ الطلب",
    from: "من",
    to: "إلى",
    admin_overview: "نظرة عامة",
    admin_users: "المستخدمون",
    admin_foods: "الأطعمة",
    admin_requests: "الطلبات",
    admin_deliveries: "التوصيلات",
    admin_analytics: "التحليلات",
    admin_dashboard: "لوحة الإدارة",
    total_users: "إجمالي المستخدمين",
    total_restaurants: "المطاعم",
    total_beneficiaries: "المستفيدون",
    total_volunteers: "المتطوعون",
    active_listings: "إعلانات نشطة",
    stats_meals_saved: "وجبات تم إنقاذها",
    active_deliveries: "توصيلات نشطة",
    success_rate: "معدل النجاح",
    waste_reduction_rate: "خفض الهدر",
    joined: "تاريخ الانضمام",
    role_label: "الدور",
    delete_user: "حذف المستخدم",
    confirm_delete: "هل أنت متأكد من حذف هذا المستخدم؟",
    user_deleted: "تم تعطيل الحساب",
    no_users: "لا يوجد مستخدمون.",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  useEffect(() => {
    const dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
    localStorage.setItem("lang", lang);
  }, [lang]);

  const t = (key) => (dict[lang] && dict[lang][key]) || dict.en[key] || key;
  const toggle = () => setLang((l) => (l === "en" ? "ar" : "en"));

  return (
    <LangContext.Provider value={{ lang, setLang, toggle, t, dir: lang === "ar" ? "rtl" : "ltr" }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
